OBJS = nw.o bioplib/ReadPIR.o bioplib/align.o bioplib/array2.o \
       bioplib/StoreString.o bioplib/OpenFile.o bioplib/GetWord.o \
       bioplib/FreeStringList.o bioplib/countchar.o

nw : $(OBJS)
	$(CC) $(LOPT) -o nw $(OBJS)

.c.o : 
	$(CC) -c -o $@ $<

clean :
	rm -f $(OBJS)

distrib : clean
	rm -f nw

